package com.mentorguild.repository.impl;


import com.mentorguild.model.Mentor;
import com.mentorguild.repository.MentorRepository;
import org.springframework.stereotype.Repository;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

@Repository
public class InMemoryMentorRepository implements MentorRepository {
    private final Map<Integer, Mentor> store = new ConcurrentHashMap<>();

    private final AtomicInteger idCounter = new AtomicInteger(1); //Atomic Integer is used because Spring Boot is automatically multithreaded by default
    //Used to generate unique IDs, must be safe under concurrency

    @Override
    //Save a mentor and return a generated ID.
    //TODO: Future create database connection so ID is generated by database
    public int save(Mentor mentor){
        int id = idCounter.getAndIncrement();
        store.put(id, mentor);
        return id;
    }

    @Override
    // Find a Mentor by ID. (Returns Optional.empty() if not found).
    public Optional<Mentor> findById(int id){
        return Optional.ofNullable(store.get(id));
    }

    @Override

    public List<Mentor> findAll(){
        return new ArrayList<>(store.values());
    }
}
