package com.mentorguild.repository.impl;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

import com.mentorguild.model.Lesson;
import com.mentorguild.repository.LessonRepository;
import org.springframework.stereotype.Repository;

/**
 * Fake repository implementation.
 * Stores Mentors in memory using a HashMap.
 * Used for development and testing.
 */
@Repository
public class InMemoryLessonRepository implements LessonRepository {
    private final Map<UUID, Lesson> store = new ConcurrentHashMap<>();

    @Override
    //Save a lesson and return a generated ID.
    //TODO: Future create database connection so ID is generated by database
    public UUID save(Lesson lesson){
        UUID id = UUID.randomUUID();
        store.put(id, lesson);
        return id;
    }

    @Override
    // Find a lesson by ID. (Returns Optional.empty() if not found).
    public Optional<Lesson> findById(UUID id){
        return Optional.ofNullable(store.get(id));
    }

    @Override

    public List<Lesson> findAll(){
        return new ArrayList<>(store.values());
    }
}
