package com.mentorguild.repository.impl;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

import com.mentorguild.model.Lesson;
import com.mentorguild.model.Mentor;
import com.mentorguild.repository.LessonRepository;
import org.springframework.stereotype.Repository;

/**
 * Fake repository implementation.
 * Stores Mentors in memory using a HashMap.
 * Used for development and testing.
 */
@Repository
public class InMemoryLessonRepository implements LessonRepository {
    private final Map<Integer, Lesson> store = new ConcurrentHashMap<>();

    private final AtomicInteger idCounter = new AtomicInteger(1); //Atomic Integer is used because Spring Boot is automatically multithreaded by default
    //Used to generate unique IDs, must be safe under concurrency

    @Override
    //Save a lesson and return a generated ID.
    //TODO: Future create database connection so ID is generated by database
    public int save(Lesson lesson){
        int id = idCounter.getAndIncrement();
        store.put(id, lesson);
        return id;
    }

    @Override
    // Find a lesson by ID. (Returns Optional.empty() if not found).
    public Optional<Lesson> findById(int id){
        return Optional.ofNullable(store.get(id));
    }

    @Override

    public List<Lesson> findAll(){
        return new ArrayList<>(store.values());
    }
}
